### PR TITLE
Overmap, Terrain and NPC rebalance.

### PR DESCRIPTION
**Pull request by Noctifer-de-Mortem**
This is a series of loosely held together changes that are too small to be their own PR. 
Here is the changelog:

-Added char creation mutations to prepper NPC class.
-Changed Survivor Emcampment and Survivor Holdout fences to palisade walls.
-Changed Survivor Holdout's skitterbots to advance zombies and wood wall and dirt floor to metal versions.
-Nerfed Bio-Weapon professions by stripping off their items and replacing with subject suits.
-Added A7 rifle in bio-weapon lab.
-Made Evelynn Rose not run away into the fight outside the Bio-Weapon's lab.
-Made the Survivor Holdout NPC wait inside the "bunker" to avoid the zombies outside.
-Made the Unknown lab be underground with the entrance a fortified bunker.

### CODE REVIEW

**Comment by chaosvolt** [comment]
Bunker change looks interesting, if small. XP

**Comment by Noctifer-de-Mortem** [comment]
It's a meant to be an entrance like the LMOE shelter.

**Comment by chaosvolt** [comment]
True. Might ponder a thing if I ever finish Wilson's potato mod.

**Comment by chaosvolt** [comment]
Well hello, bunker. Secret bunker is secret.

image

**Comment by chaosvolt** [comment]
Tried tweaking something and got better results:
image

```
    }, {
        "type" : "overmap_special",
        "id" : "Unknown_Lab_s",
        "overmaps" :
        [
            
            { "point":[0,0,0], "overmap": "Unknown_Bunker"},
			{ "point":[0,0,-1], "overmap": "Unknown_Lab"}
        ],
        "connections" : [
            { "point" : [0,-1,0], "terrain" : "road" }
        ],
        "locations" : [ "wilderness", "swamp" ], "//":"what special locations does it spawn",
        "city_distance" : [20, -1], "//":"how far from a city it should be",
        "city_sizes" : [0, 16], "//":"what city sizes should it spawn in",
        "occurrences" : [1, 1], "//":"how many per overmap",
        "rotate" : false, "//":"allow rotation",
        "unique" : true, "//":"only allow one per city",
        "required" : true, "//":"is this special required for valid city sizes",
        "flags" : [ "CLASSIC", "UNIQUE" ]
    }, {
```

**Pull request merged**
